name: beacon_broadcast
description: A Flutter plugin for turning your device into a beacon. Plugin uses AltBeacon library for Android and
  CoreLocation for iOS.
version: 0.0.1
homepage: https://github.com/darmawan01/beacon_broadcast

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: pl.pszklarska.beaconbroadcast
        pluginClass: BeaconBroadcastPlugin
      ios:
        pluginClass: BeaconBroadcastPlugin