name: beacon_broadcast
description: A Flutter plugin for turning your device into a beacon. Plugin uses AltBeacon library for Android and
  CoreLocation for iOS.
version: 0.3.2
homepage: https://github.com/rtorrecilhas/beacon_broadcast

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.17.10
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: pl.pszklarska.beaconbroadcast
        pluginClass: BeaconBroadcastPlugin
      ios:
        pluginClass: BeaconBroadcastPlugin